export const SET_PRODUCTS = 'SET_PRODUCTS';
export const UPDATE_PRODUCT_FEATURED = 'UPDATE_PRODUCT_FEATURED';
export const UPDATE_PRODUCT_PRICE = 'UPDATE_PRODUCT_PRICE';
export const UPDATE_PRODUCT_STATUS = 'UPDATE_PRODUCT_STATUS';

export const SET_ORDERS = 'SET_ORDERS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
