version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@0.1.20

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
      - run:
          command: npm run test
      - run:
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*

  deploy:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - attach_workspace:
          at: build
      - aws-cli/setup
      - run:
          name: Upload build files
          command: aws s3 sync build ${S3_BUCKET} --acl public-read --delete
      - run:
          name: Invalidate CloudFront Cache
          command: |
            aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION} --paths "/*"


workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          context: aws
          requires:
            - build-and-test
          filters:
            branches:
              only: main